baseURL = "https://ggi.castalia.camp/"
languageCode = "en-us"
title = "OSS Good Governance Initiative"
theme = "hugo-html5up-alpha"

[params]
  #description = "Another fine responsive site template freebie by HTML5 UP."
  #images = ["images/background.jpg"]
  author = "Licence: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0)"
  copyright = "© 2021 GGI. All rights reserved."
  mainSections = ["activities"]

### Footer Social Media Links ###
[[params.share]]
title = "facebook"
icon = "fa-facebook-f" # fontawesome icons Https://Fontawesome.Com/Icons?D=Gallery&S=Brands
link = "https://www.ow2.org/view/OSS_Governance/"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "https://www.ow2.org/view/OSS_Governance/"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://www.ow2.org/view/OSS_Governance/"

### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "goals"
    name = "Goals"
    url = "/goals/"
    weight = 30
  [[menu.main]]
    identifier = "activities"
    name = "Activities"
    url = "/activities/"
    weight = 40
  [[menu.main]]
    identifier = "contributing"
    name = "Contributing"
    url = "/contributing"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 0
  # [[menu.main]]
  #   identifier = "submenu"
  #   name = "Submenu"
  #   url = "#"
  #   weight = 50
  # [[menu.main]]
  #   parent = "submenu"
  #   identifier = "one"
  #   name = "Option One"
  #   url = "#"
  #   weight = 51
  # [[menu.main]]
  #   parent = "submenu"
  #   identifier = "two"
  #   name = "Option Two"
  #   url = "#"
  #   weight = 52
  # [[menu.main]]
  #   parent = "submenu"
  #   identifier = "three"
  #   name = "Option Three"
  #   url = "#"
  #   weight = 53
  # [[menu.main]]
  #   parent = "submenu"
  #   identifier = "four"
  #   name = "Option Four"
  #   url = "#"
  #   weight = 54
